=== yanisamrouche/Post-relational-data/Devoir/site-master.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT site-master (intervenants, parcours*)>

<!--Les intervenants-->
<!ELEMENT intervenants (intervenant+)>
<!ELEMENT intervenant (nom, adresse)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT adresse (mail | site-web)*>
<!ELEMENT mail (#PCDATA)>
<!ELEMENT site-web (#PCDATA)>
<!--Attribut pour l'element intervenant-->
<!ATTLIST intervenant id ID #REQUIRED>

<!--Les parcours-->
<!ELEMENT parcours (nom,  lieu+, responsable+, description?, semestre+, liste-debouches?)>
<!ELEMENT responsable (#PCDATA)>
<!ELEMENT lieu (#PCDATA)>
<!ELEMENT description (texte)>
<!ELEMENT semestre (ue-obligatoires, ue-optionnelles*)>
<!ELEMENT liste-debouches (texte)>
<!ELEMENT texte (#PCDATA | ul | p | table | a)*>
<!ELEMENT ul (li+)>
<!ELEMENT li (#PCDATA)>
<!ELEMENT p (#PCDATA)>
<!ELEMENT table (th*, tr*)>
<!ELEMENT th (#PCDATA)>
<!ELEMENT tr (td*)>
<!ELEMENT td (#PCDATA)>
<!ELEMENT a  ANY>
<!--Attribut pour les elements du parcours-->
<!ATTLIST semestre id (S1 | S2 | S3| S4) #REQUIRED>
<!ATTLIST parcours code ID #REQUIRED>
<!ATTLIST responsable ref IDREF #REQUIRED>
<!ATTLIST a  href CDATA #REQUIRED>


<!--Les unites-->
<!ELEMENT ue-obligatoires (unite+)>
<!ELEMENT ue-optionnelles (unite+)>
<!ELEMENT unite (nom, nombre-credits, ref-intervenant+, resume, plan?, lieu?)>
<!ELEMENT nombre-credits (#PCDATA)>
<!ELEMENT resume (texte)?>
<!ELEMENT plan (texte)>
<!--Attribut pour les unites-->
<!ATTLIST ue-optionnelles credits-options CDATA #REQUIRED>
<!ATTLIST unite id (SINAU01 |SINAU02 |SINAU03 |SINAU04 |SINAU05 |SINAU06 |SINAU07 |SINAU08 |SINBU01 |SINBX01 |SINBX02 |SINBX03 | SINAU1 | SINAU3 | ENSINBU4 | SINBU03 | SINBU30 | SINBU29 | SINDU06L | SINDU01 | SINDU02 | SINCU92L | SINCU01L | SINCUA4L | SINCUA3 | SINCU02 | SINCU04 | SINCU06 | SINCU89 | SINCU97 | SINDU05 | SINCU01J | SINCU99J|SINCU98L|SINCUA1L|SINDU01L|SINDU01J | SINDU02J | SINCU01I | SINBU07L ) #REQUIRED>

<!--ref intervenant-->
<!ELEMENT ref-intervenant ANY>
<!ATTLIST ref-intervenant ref IDREF #IMPLIED>

<!--
    les entitÃ©s
<!ENTITY dom.mail-mrs "univ-mrs.fr">
<!ENTITY dom.mail-amu "univ-amu.fr">
<!ENTITY dom.lieu-luminy "Luminy">
<!ENTITY dom.lieu-saint-jerome "Saint-Jerome">
-->

=== yanisamrouche/Post-relational-data/Devoir/site-master.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE site-master SYSTEM "site-master.dtd"[
        <!ENTITY dom.mail-mrs "univ-mrs.fr">
        <!ENTITY dom.mail-amu "univ-amu.fr">
        <!ENTITY dom.lieu-luminy "Luminy">
        <!ENTITY dom.lieu-saint-jerome "Saint-Jérôme">
]>
<site-master>
    <intervenants>
        <intervenant id="Jean-Luc_MASSAT">
            <nom>Jean-Luc-MASSAT</nom>
            <adresse>
                <mail>jean-luc-massat@univ-amu.fr</mail>
                <site-web>http://pageperso.lif.univ-mrs.fr/~jean-luc.massat/</site-web>   
            </adresse>
    </intervenant>
    <intervenant id="Remi_MORIN">
            <nom>Rémi MORIN</nom>
            <adresse>
                <mail>remi.morin@univ-amu.fr</mail>
                <site-web>http://pageperso.lif.univ-mrs.fr/~remi.morin/</site-web>
            </adresse>
        </intervenant>
    <intervenant id="Kevin_PERROT">
            <nom>Kevin PERROT</nom>
            <adresse>
                <mail>kevin.perrot@lif.univ-mrs.fr</mail>
                <site-web>http://pageperso.lif.univ-mrs.fr/~kevin.perrot/</site-web>
            </adresse>
    </intervenant>
    <intervenant id="Djamal_HABET">
            <nom>Djamal HABET</nom>
            <adresse>
                <mail>djamal.habet@univ-amu.fr</mail>
                <site-web>https://pageperso.lis-lab.fr/djamal.habet/</site-web>
            </adresse>
    </intervenant>
    <intervenant id="Omar_BOUCELMA">
            <nom>Omar BOUCELMA</nom>
            <adresse>
                <mail>omar.boucelma@univ-amu.fr</mail>
                <site-web>https://annuaire.univ-amu.fr/personnel/detail/b21hci5ib3VjZWxtYQ==</site-web>
            </adresse>
    </intervenant>
    <intervenant id="Noel_NOVELLI">
            <nom>Noël Novelli</nom>
            <adresse>
                <mail>noel.novelli@univ-amu.fr</mail>
                <site-web>https://pageperso.lis-lab.fr/noel.novelli/</site-web>
            </adresse>
    </intervenant>
    <intervenant id="Emmanuel_GODARD">
            <nom>Emmanuel GODARD</nom>
            <adresse>
                <mail>emmanuel.godard@univ-amu.fr</mail>
                <site-web>https://pageperso.lis-lab.fr/emmanuel.godard/index.html</site-web>
            </adresse>
    </intervenant>
     <intervenant id="Philippe_Jegou">
            <nom>Philippe Jegou</nom>
            <adresse>
                <mail>philippe.jegou@univ-amu.fr</mail>
                <site-web>https://www.researchgate.net/profile/Philippe-Jegou</site-web>
            </adresse>
    </intervenant>
     <intervenant id="Maamar_El-Amine_HAMRI">
            <nom>Maâmar El-Amine HAMRI </nom>
            <adresse>
                <mail>amine.hamri@lsis.org</mail>
                <site-web>http://www.liophant.org/iepal/u_us3/cv_f_a.html</site-web>
            </adresse>
    </intervenant>
         <intervenant id="GRAINGER_Thomas">
            <nom>GRAINGER Thomas</nom>
            <adresse>
                <mail>tom.grainger@univ-amu.fr</mail>
                <site-web>https://www.arounddeal.com/profile/tom-grainger/b4dcfnansx/</site-web>
            </adresse>
    </intervenant>
    <intervenant id="CONTENSIN_Magali">
        <nom>CONTENSIN Magali</nom>
        <adresse>
            <mail>magali.contensin@univ-amu.fr</mail>
            <site-web>le site est non rensigné </site-web>
        </adresse>
    </intervenant>
    <intervenant id="ROMANO_Christian">
        <nom>ROMANO Christian</nom>
        <adresse>
            <mail>christian.ROMANO@univ-amu.fr</mail>
            <site-web>https://copainsdavant.linternaute.com/p/christian-romano-20127144</site-web>
        </adresse>
    </intervenant>
    <intervenant id="HOAREAU_Nicolas">
        <nom>HOAREAU Nicolas</nom>
        <adresse>
            <mail>nicolasO.HOAREAU@univ-amu.fr</mail>
            <site-web>https://fr.linkedin.com/in/nicolas-hoareau-craftedbits</site-web>
        </adresse>
    </intervenant>
    <intervenant id="Clara_BERTOLISSI">
        <nom>Clara BERTOLISSI</nom>
        <adresse>
            <mail>clara.bertolissi@univ-amu.fr</mail>
            <site-web>https://pageperso.lis-lab.fr/~clara.bertolissi/</site-web>
        </adresse>
    </intervenant>
    <intervenant id="Roland_AGOPIAN">
        <nom>Roland AGOPIAN</nom>
        <adresse>
            <mail>roland.agopian@univ-amu.fr</mail>
            <site-web>https://jorfsearch.steinertriples.fr/Q2302586</site-web>
        </adresse>
    </intervenant>
    </intervenants>

   <parcours code="M1">
        <nom>Première année de tronc commun</nom>
        <lieu>Luminy</lieu>
        <lieu>Saint-Jérôme</lieu>
        <responsable ref="Remi_MORIN"/>
        <description>
            <texte>
                <p>L'objectif de cette première année est de donner les bases indispensables permettant, en deuxième année, de choisir une spécialisation dans un domaine précis. Sur les 60 crédits de cette première année, 15 crédits correspondent à des enseignements optionnels. Ces options permettent de construire un parcours adapté. Un choix entre stage ou projet encadré est également proposé au semestre de printemps.</p>
            </texte>
        </description>

        <semestre id="S1"> 
            <ue-obligatoires>
                <unite id="SINAU02">
                    <nom>Génie Logiciel</nom>
                    <nombre-credits>6</nombre-credits>
                    <ref-intervenant ref="Maamar_El-Amine_HAMRI"/>
                    <ref-intervenant ref="Kevin_PERROT"/>
                    <resume>
                        <texte>
                            <ul>
                                <li>Introduction au génie logiciel</li>
                                <li>Gestion de projet</li>
                                <li>Méthodes (Spécification et conception)</li>
                                <li>UML et Design patterns</li>
                            </ul>
                        </texte>
                    </resume>
                    <plan>
                            <texte>
                            <ul>
                                <li>chapitre 01 : ...</li>
                                <li>chapitre 02 : ...</li>
                                <li>chapitre 03 : ...</li>
                                <li>chapitre 04 : ...</li>
                            </ul>
                            </texte>
                    </plan>
                    <lieu>Luminy</lieu>
                </unite>
                <unite id="SINAU05">
                    <nom>Programmation objet concurrente</nom>
                    <nombre-credits>3</nombre-credits>
                    <ref-intervenant ref="Remi_MORIN"/>
                    <resume>
                        <texte>
                         Cette UE présente aux étudiants du M1 les principales difficultés de la programmation multi-thread et les techniques classiques permettant de développer un code correct et performant.
                        </texte>
                    </resume>
                    <plan>
                            <texte>
                            <ul>
                                <li>chapitre 01 : ...</li>
                                <li>chapitre 02 : ...</li>
                                <li>chapitre 03 : ...</li>
                                <li>chapitre 04 : ...</li>
                            </ul>
                            </texte>
                    </plan>
                    <lieu>Luminy</lieu>
                </unite>       
                <unite id="SINAU3">
                    <nom>Complexité</nom>
                    <nombre-credits>6</nombre-credits>
                    <ref-intervenant ref="Philippe_Jegou"/>
                   
                    <resume>
                        <texte>
                            <ul>
                                <li>Rappels sur les notions d'analyse de la complexité des algorithmes et des problèmes.</li>
                                <li>Notion de problèmes (décision, recherche, dénombrement, énumération, optimisation). Bornes inférieures de complexité.</li>
                                <li>Classes P et NP. Problèmes NP-complets.</li>
                                <li>Méthodes de résolution des problèmes NP-Complets.</li>
                            </ul>
                        </texte>
                    </resume>
                    <plan>
                            <texte>
                            <ul>
                                <li>chapitre 01 : ...</li>
                                <li>chapitre 02 : ...</li>
                                <li>chapitre 03 : ...</li>
                                <li>chapitre 04 : ...</li>
                            </ul>
                            </texte>
                    </plan>
                    <lieu>Luminy</lieu>
                </unite>           
                <unite id="SINAU06">
                    <nom>Réseaux</nom>
                    <nombre-credits>6</nombre-credits>
                    <ref-intervenant ref="Djamal_HABET"/>
                    <resume>
                        <texte>
                            <ul>
                                <li>Architecture en couches, standard OSI</li>
                                <li>Couche physique</li>
                                <li>Couche liaison de Données</li>
                                <li>Réseau IP</li>
                                <li>Algorithmes de routage, routage IP</li>
                                <li>Protocole TCP/IP</li>
                                <li>Couche Application : HTTP, SMTP, FTP, ...</li>
                                <li>Bases des protocoles cryptographiques (terminologie, architecture à clef publique).</li>
